### ISSUE TITLE
《   ·  〈 〉﹑ ﹔ not in punctuation list of hanzi 

### ISSUE THREAD

**Issue by rudaoshi** [tsroten/zhon#19]
《   ·  〈 〉﹑ ﹔   this symbols are missing in punctuation list of hanzi

**Comment by tsroten** [comment]
@rudaoshi Thanks for reporting these missing punctuation marks. The changes have been pushed to the `develop` branch of the repository.

**Comment by tsroten** [comment]
@rudaoshi This fix has been pushed to PyPI in zhon version 1.1.4.
