### ISSUE TITLE
pinyin regex matches junk

### ISSUE THREAD

**Issue by bcaller** [tsroten/zhon#21]
`re.findall(zhon.pinyin.numbered_syllable, 'foo bar', re.IGNORECASE)`
...`['fo', 'o', 'ba', 'r']`

`re.findall(zhon.pinyin.syllable, 'foo bar', re.IGNORECASE)`
... `['fo', 'o', 'ba', 'r']`

same for accented_syllable

I was hoping for a way to match only pinyin within mixed English text.

**Comment by tsroten** [comment]
@bcaller Thanks for using zhon!

This is actually the intended behavior of the syllable constants. The syllables returned above are all valid Pinyin syllables (`fo`, `o`, `ba`, and `r`). You can see all of these syllables in a dictionary such as [mdbg.net](http://www.mdbg.net/).

If you are trying to find Pinyin text amidst English, you should use the word constants (i.e. `zhon.pinyin.accented_word`, `zhon.pinyin.numbered_word`, and `zhon.pinyin.word`). They respect word boundaries and should be able to work within English text (as long as the English words aren't also valid Pinyin words)

**Comment by bcaller** [comment]
My problem was that many English words such as 'are' are valid. Never mind, I found a better way using a slightly less precise regex. Nice library by the way. I realise now that your original use case was probably more for text that you know is definitely pinyin but you want to type it with numbers and get accents.
