### ISSUE TITLE
Pinyin.syllable truncates 'beì' (accented_syllable, and word)

### ISSUE THREAD

**Issue by jct888** [tsroten/zhon#26]
Using the zhon.pinyon package, the pinyin (utf-8) syllable 'beì' in a regular expression, does not match perfectly.  In fact, beì gets truncated to 'e', despite all other pinyin tried so far (~1,000).

Here's an example from Terminal in Mac OS X 10.11.6 and Python 2.7:
```
>>> import re
>>> import zhon.pinyin
>>> ln = u'南 ná 無 mó 善 shàn 臂 beì 菩薩 pú sà'
>>> pyo = re.findall(zhon.pinyin.syllable, ln)
>>> pyo
[u'n\xe1', u'm\xf3', u'sh\xe0n', u'e', u'p\xfa', u's\xe0']
                                                  ^ missing 'b' and 'ì'
```

**Comment by tsroten** [comment]
@jct888 Hi! Thanks for using Zhon. Zhon is strict about where the accent mark should be placed. If there is an `e` in the syllable, then [it always receives the tone mark](http://pinyin.info/rules/where.html). So, try `bèi` instead.

**Comment by jct888** [comment]
We tried bèi before, and it does, indeed, work.  This is a 10K+ line of text project.  Very glad your project exists; this is the only 'gotcha' found, and I'm learning a lot of Pinyin.  Thank you!

**Comment by tsroten** [comment]
@jct888 Great! Another project you might find helpful as you work with Pinyin and Chinese text is [Dragon Mapper](https://github.com/tsroten/dragonmapper). It has an easy-to-use Pinyin validator [`dragonmapper.transcriptions.is_pinyin()`](http://dragonmapper.readthedocs.io/en/latest/tutorial.html#identifying-transcription-systems).

**Comment by jct888** [comment]
Thanks! Detecting Pinyin and English lines, mixed or 'only', is one of the tests needed.  Starting with accented_syllable, and extracting the Unicode chars with accents helped. That's an amazing literal!
