### ISSUE TITLE
AttributeError: module 'zhon' has no attribute 'hanzi'

### ISSUE THREAD

**Issue by woshichuanqilz** [tsroten/zhon#28]
got no attribute hanzi, 

>>> import zhon
>>> zhon.hanzi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'zhon' has no attribute 'hanzi'

I don't know why seems the package install correct. 

![20180120175620](http://7xpvdr.com1.z0.glb.clouddn.com/0120175613.png)

Same with others
![20180120175742](http://7xpvdr.com1.z0.glb.clouddn.com/0120175735.png)

I use windows 10 anaconda 3

**Comment by tsroten** [comment]
Hi @woshichuanqilz! You have to explicitly import the module you would like (since it reads a bunch of data into memory):

```python
import zhon.hanzi
```

OR 
```python
from zhon import hanzi
```
